from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    HRFlowable, Table, TableStyle, PageBreak, KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import tempfile
from typing import List, Dict
from datetime import datetime


def build_presenter_pdf(
    slides: List[Dict],
    title: str,
    subject: str,
    level: str,
    language: str,
) -> str:
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    tmp.close()

    doc = SimpleDocTemplate(
        tmp.name,
        pagesize=A4,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    PAGE_W = A4[0] - (0.75 * inch * 2)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("DocTitle", parent=styles["Title"],
        fontSize=20, textColor=colors.HexColor("#003366"),
        spaceAfter=4, alignment=TA_CENTER, fontName="Helvetica-Bold")
    meta_style = ParagraphStyle("Meta", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#666666"),
        alignment=TA_CENTER, spaceAfter=2)
    disclaimer_style = ParagraphStyle("Disclaimer", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#888888"),
        alignment=TA_CENTER, spaceAfter=20)
    slide_num_style = ParagraphStyle("SlideNum", parent=styles["Normal"],
        fontSize=9, textColor=colors.white,
        fontName="Helvetica-Bold", alignment=TA_LEFT)
    slide_title_style = ParagraphStyle("SlideHeading", parent=styles["Normal"],
        fontSize=13, textColor=colors.white,
        fontName="Helvetica-Bold", alignment=TA_LEFT)
    badge_style = ParagraphStyle("Badge", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#D4AF37"),
        fontName="Helvetica-Bold", spaceAfter=5)
    content_label_style = ParagraphStyle("ContentLabel", parent=styles["Normal"],
        fontSize=9, textColor=colors.HexColor("#003366"),
        fontName="Helvetica-Bold", spaceBefore=8, spaceAfter=4)
    bullet_style = ParagraphStyle("Bullet", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#1a1a1a"),
        leftIndent=14, spaceAfter=4, leading=14)
    notes_style = ParagraphStyle("Notes", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#1a1a1a"),
        leading=15, spaceAfter=4)
    ref_style = ParagraphStyle("Ref", parent=styles["Normal"],
        fontSize=9, textColor=colors.HexColor("#1a1a1a"),
        leftIndent=18, firstLineIndent=-18, leading=13, spaceAfter=6)
    ref_warning_style = ParagraphStyle("RefWarning", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#AA4400"),
        fontName="Helvetica-Oblique", spaceAfter=12, alignment=TA_CENTER)

    story = []

    # Cover
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("PRESENTER NOTES", meta_style))
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(f"{subject}  •  {level} Level", meta_style))
    story.append(Paragraph(
        f"Generated by pptPro  •  {datetime.now().strftime('%B %d, %Y')}",
        meta_style))
    story.append(Spacer(1, 0.12 * inch))
    story.append(HRFlowable(width="100%", thickness=2,
        color=colors.HexColor("#D4AF37"), spaceAfter=10))
    story.append(Paragraph(
        "⚠️  AI-generated content. Verify all facts and references before presenting.",
        disclaimer_style))

    SKIP_TYPES = {"title", "toc", "references"}
    ACCENT_COLOR = colors.HexColor("#003366")
    NOTES_BG = colors.HexColor("#EBF2FF")
    NOTES_BORDER = colors.HexColor("#003366")
    DIVIDER_COLOR = colors.HexColor("#cccccc")

    for i, slide in enumerate(slides):
        stype = slide.get("slide_type", "")
        if stype in SKIP_TYPES:
            continue

        slide_name = slide.get("slide_name", f"Slide {i + 1}")
        heading = slide.get("heading", slide_name)
        content = slide.get("content", [])
        notes = slide.get("notes", "")

        block = []

        header_table = Table(
            [[Paragraph(f"#{i + 1}", slide_num_style),
              Paragraph(heading, slide_title_style)]],
            colWidths=[0.5 * inch, PAGE_W - 0.5 * inch],
        )
        header_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), ACCENT_COLOR),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        block.append(header_table)
        block.append(Spacer(1, 0.05 * inch))
        block.append(Paragraph(f"[ {slide_name.upper()} ]", badge_style))

        if content:
            block.append(Paragraph("SLIDE CONTENT", content_label_style))
            for item in content:
                block.append(Paragraph(f"•  {item}", bullet_style))

        block.append(Spacer(1, 0.06 * inch))

        if notes:
            block.append(Paragraph("PRESENTER NOTES", content_label_style))
            notes_table = Table(
                [[Paragraph(notes, notes_style)]], colWidths=[PAGE_W])
            notes_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), NOTES_BG),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("BOX", (0, 0), (-1, -1), 1, NOTES_BORDER),
            ]))
            block.append(notes_table)

        block.append(Spacer(1, 0.14 * inch))
        block.append(HRFlowable(width="100%", thickness=0.5,
            color=DIVIDER_COLOR, spaceAfter=10))
        story.append(KeepTogether(block))

    # References page
    ref_slide = next((s for s in slides if s.get("slide_type") == "references"), None)
    if ref_slide:
        story.append(PageBreak())
        story.append(Paragraph("REFERENCES", title_style))
        story.append(HRFlowable(width="100%", thickness=1.5,
            color=colors.HexColor("#D4AF37"), spaceAfter=10))
        story.append(Paragraph(
            "⚠️  AI-generated references. Verify each one before submitting.",
            ref_warning_style))
        for ref in ref_slide.get("content", []):
            story.append(Paragraph(ref, ref_style))

    doc.build(story)
    return tmp.name
